name: Seed MongoDB
on:
  push:
    paths:
      - '.github/workflows/seed.yml'
jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          cd backend
          npm install mongodb mongoose dotenv
          
      - name: Run Seeding Script
        run: |
          cd backend
          node scripts/seedFromDump.js
        env:
          MONGODB_URI: "mongodb+srv://malikirtaza2003_db_user:uyTNeb902XVWSuLA@cluster0.fkfughv.mongodb.net/saas_web_app?retryWrites=true&w=majority&appName=Cluster0"
